In [6]:
import pandas as pd
import os

# Change the current directory to the new directory
os.chdir('D:/Cssci/terrorism/group-project-5')

# load dataset
df = pd.read_excel('data/globalterrorismdb_0522dist.xlsx')

In [4]:
os.getcwd()

'D:\\Cssci\\terrorism\\group-project-5'

In [8]:
save_df = df # store the original dataset in a temporary dataframe so we don't need to load the dataset everytime

In [47]:
df = save_df

In [9]:
display(df)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaT,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaT,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaT,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaT,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaT,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209701,202012310015,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209702,202012310016,2020,12,31,2020-12-31 00:00:00,0,NaT,228,Yemen,10,...,NaN,"""Al Houthi militia escalated in Hays and targe...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
209703,202012310017,2020,12,31,NaN,0,NaT,75,Germany,8,...,NaN,"""Far-left arson attack suspected on German asy...","""Fire of Bundeswehr vehicles in Leipzig, proba...","""Anarchist Antifa Take Credit for Arson Attack...",START Primary Collection,-9,-9,0,-9,NaN
209704,202012310018,2020,12,31,NaN,0,NaT,4,Afghanistan,6,...,NaN,"""Civil society activist and tribal elder kille...","""Terrorism Digest: 1-2 Jan 21,"" BBC Monitoring...",NaN,START Primary Collection,-9,-9,0,-9,NaN
209705,202012310019,2020,12,31,NaN,1,NaT,33,Burkina Faso,11,...,NaN,"""Terrorism Digest: 3-4 Jan 21,"" BBC Monitoring...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [10]:
df = df[['attacktype1_txt','weaptype1_txt','multiple','success','doubtterr','nkill','nwound','nhostkid']]

In [4]:
display(df)

        attacktype1  weaptype1  multiple  success  doubtterr  nkill  nwound
0                 1         13       0.0        1          0    1.0     0.0
1                 6         13       0.0        1          0    0.0     0.0
2                 1         13       0.0        1          0    1.0     0.0
3                 3          6       0.0        1          0    NaN     NaN
4                 7          8       0.0        1         -9    NaN     NaN
...             ...        ...       ...      ...        ...    ...     ...
209701            3          6       0.0        1          0    NaN     NaN
209702            3          6       0.0        1          0    NaN     NaN
209703            7          8       0.0        1          1    0.0     0.0
209704            2          5       0.0        1          0    1.0     0.0
209705            2          5       0.0        1          1    5.0     0.0

[209706 rows x 7 columns]

In [11]:
df["severity"] = df['nkill'] + df ["nwound"]
df = pd.get_dummies(df, columns=['attacktype1_txt', 'weaptype1_txt'])
df.drop(columns=['attacktype1_txt_Unknown', 'weaptype1_txt_Unknown'], inplace=True)

C:\Users\13911\AppData\Local\Temp\ipykernel_12192\3244389804.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["severity"] = df['nkill'] + df ["nwound"]

In [12]:
display(df)

,multiple,success,doubtterr,nkill,nwound,nhostkid,severity,attacktype1_txt_Armed Assault,attacktype1_txt_Assassination,attacktype1_txt_Bombing/Explosion,...,weaptype1_txt_Chemical,weaptype1_txt_Explosives,weaptype1_txt_Fake Weapons,weaptype1_txt_Firearms,weaptype1_txt_Incendiary,weaptype1_txt_Melee,weaptype1_txt_Other,weaptype1_txt_Radiological,weaptype1_txt_Sabotage Equipment,"weaptype1_txt_Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)"
0,0.0,1,0,1.0,0.0,NaN,1.0,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,0.0,1,0,0.0,0.0,1.0,0.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0.0,1,0,1.0,0.0,NaN,1.0,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,0.0,1,0,NaN,NaN,NaN,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
4,0.0,1,-9,NaN,NaN,NaN,NaN,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209701,0.0,1,0,NaN,NaN,NaN,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
209702,0.0,1,0,NaN,NaN,NaN,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
209703,0.0,1,1,0.0,0.0,NaN,0.0,False,False,False,...,False,False,False,False,True,False,False,False,False,False
209704,0.0,1,0,1.0,0.0,NaN,1.0,True,False,False,...,False,False,False,True,False,False,False,False,False,False
209705,0.0,1,1,5.0,0.0,NaN,5.0,True,False,False,...,False,False,False,True,False,False,False,False,False,False

In [13]:
# Fill missing values with zero
df.fillna(0, inplace=True)

# Convert the DataFrame to integer type
df = df.astype(int)

In [14]:
import statsmodels.api as sm

X = df.drop(columns=['nkill','nwound','severity','nhostkid'])
y = df['nhostkid'] 
X = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X).fit()

# Print the summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               nhostkid   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     5.071
Date:                Mon, 26 Feb 2024   Prob (F-statistic):           5.87e-14
Time:                        14:01:02   Log-Likelihood:            -1.1247e+06
No. Observations:              209706   AIC:                         2.249e+06
Df Residuals:                  209683   BIC:                         2.250e+06
Df Model:                          22
Covariance Type:            nonrobust
=============================================================================================================================================================
                                                                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                         0.1095      0.576      0.190      0.849      -1.020       1.239
multiple                                                                                     -0.4501      0.325     -1.387      0.166      -1.086       0.186
success                                                                                       0.4803      0.361      1.329      0.184      -0.228       1.188
doubtterr                                                                                     0.0905      0.050      1.805      0.071      -0.008       0.189
attacktype1_txt_Armed Assault                                                                 1.3587      0.847      1.604      0.109      -0.302       3.019
attacktype1_txt_Assassination                                                                 0.9159      0.856      1.070      0.285      -0.763       2.594
attacktype1_txt_Bombing/Explosion                                                             0.1246      0.980      0.127      0.899      -1.795       2.044
attacktype1_txt_Facility/Infrastructure Attack                                                1.1773      1.051      1.120      0.263      -0.883       3.238
attacktype1_txt_Hijacking                                                                     9.0605      2.013      4.500      0.000       5.114      13.007
attacktype1_txt_Hostage Taking (Barricade Incident)                                          -7.2467      1.693     -4.281      0.000     -10.565      -3.929
attacktype1_txt_Hostage Taking (Kidnapping)                                                   3.2765      0.760      4.310      0.000       1.787       4.766
attacktype1_txt_Unarmed Assault                                                               0.9357      1.977      0.473      0.636      -2.938       4.810
weaptype1_txt_Biological                                                                     -1.0871      8.810     -0.123      0.902     -18.354      16.180
weaptype1_txt_Chemical                                                                       -1.3343      3.059     -0.436      0.663      -7.329       4.661
weaptype1_txt_Explosives                                                                     -0.5788      0.836     -0.692      0.489      -2.217       1.060
weaptype1_txt_Fake Weapons                                                                   22.2045      8.807      2.521      0.012       4.943      39.466
weaptype1_txt_Firearms                                                                       -1.6013      0.659     -2.429      0.015      -2.894      -0.309
weaptype1_txt_Incendiary                                                                     -1.7568      0.920     -1.910      0.056      -3.559       0.046
weaptype1_txt_Melee                                                                          -1.7420      1.028     -1.695      0.090      -3.756       0.272
weaptype1_txt_Other                                                                           0.0406      4.539      0.009      0.993      -8.856       8.937
weaptype1_txt_Radiological                                                                   -0.7080     14.455     -0.049      0.961     -29.040      27.624
weaptype1_txt_Sabotage Equipment                                                             -1.4319      3.883     -0.369      0.712      -9.042       6.178
weaptype1_txt_Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)    -0.8001      4.060     -0.197      0.844      -8.757       7.157
==============================================================================
Omnibus:                  1059476.377   Durbin-Watson:                   1.381
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   36220911409681.359
Skew:                         224.023   Prob(JB):                         0.00
Kurtosis:                   64385.726   Cond. No.                         304.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [45]:
import sys
with open('model_summary.txt', 'w') as f:
    # Redirect stdout to the file
    sys.stdout = f
    # Print the model summary
    print(model.summary())
    # Reset stdout
    sys.stdout = sys.__stdout__

# Read the saved text file and display its contents
with open('model_summary.txt', 'r') as f:
    print(f.read())

In [61]:
with open('nhostkid.html', 'w') as f:
    f.write(model.summary().as_html())